### ISSUE TITLE
find_one_and_delete not working in prod mongo from the alertor

### ISSUE THREAD

**Issue by jparicka** [ProjectCloudly/Cloudly#614]
Traceback (most recent call last):
  File "alertor.py", line 71, in <module>
    alert = alertor_queue.find_one_and_delete({})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1489, in __call__
    self.__name.split(".")[-1])
TypeError: 'Collection' object is not callable. If you meant to call the 'find_one_and_delete' method on a 'Collection' object it is failing because no such method exists.

**Comment by jparicka** [comment]
fixed
