### ISSUE TITLE
API crashes

### ISSUE THREAD

**Issue by OndrejKopal** [ProjectCloudly/Cloudly#631]
Traceback (most recent call last):                                                                                                       
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__                                                           
    return self.wsgi_app(environ, start_response)                                                                                        
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app                                                           
    response = self.make_response(self.handle_exception(e))                                                                              
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception                                                   
    reraise(exc_type, exc_value, tb)                                                                                                     
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app                                                           
    response = self.full_dispatch_request()                                                                                              
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request                                              
    rv = self.handle_user_exception(e)                                                                                                   
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception                                              
    reraise(exc_type, exc_value, tb)                                                                                                     
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request                                              
    rv = self.dispatch_request()                                                                                                         
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request                                                   
    return self.view_functions[rule.endpoint](**req.view_args)                                                                           
  File "/home/cloudly/cloudly/api.py", line 56, in activity                                                                              
    'server_id': data['server_id'],                                                                                                      
KeyError: 'server_id'                                                                                                                    
API query from agent version 0.3 52:54:00:00:42:eb IP 127.0.0.1/46.28.109.25 uptime 44 days, 11:27

**Comment by jparicka** [comment]
fixed
