### ISSUE TITLE
work in netfilter immunity on the agent

### ISSUE THREAD

**Issue by jparicka** [ProjectCloudly/Cloudly#643]
The "Another app is currently holding the xtables lock. Perhaps you want to use the -w option?" .. error.

2015-12-21 15:25:34.713250 Collected system metrics..
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Traceback (most recent call last):
  File "monitoring-agent.py", line 866, in <module>
    main()
  File "monitoring-agent.py", line 840, in main
    system_metrics = get_system_metrics(UUID, SECRET)
  File "monitoring-agent.py", line 784, in get_system_metrics
    networking = _get_networking_stats()
  File "monitoring-agent.py", line 596, in _get_networking_stats
    inbound_traffic['input_accept_packets'] = input_accept_packets
UnboundLocalError: local variable 'input_accept_packets' referenced before assignment
restarting the agent...

**Comment by jparicka** [comment]
fixed
