### ISSUE TITLE
API ocassionally reports problem with some agents

### ISSUE THREAD

**Issue by jparicka** [ProjectCloudly/Cloudly#654]
52.18.0.152 - - [24/Dec/2015 12:58:53] "POST /v10/ping/ HTTP/1.1" 500 -
Traceback (most recent call last):   
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloudly/cloudly/api.py", line 411, in ping
    current_alert_duration = (datetime.datetime.now()-last_active_service_status['date']).total_seconds()
KeyError: 'date'

**Comment by jparicka** [comment]
fixed
