### ISSUE TITLE
bug in the monitoring-agent _get_networking_stats

### ISSUE THREAD

**Issue by sfrostick** [ProjectCloudly/Cloudly#703]
OS: Ubuntu 14.04

Error:
```
Traceback (most recent call last):
  File "/opt/monitoring-agent.py", line 891, in <module>
    main()
  File "/opt/monitoring-agent.py", line 846, in main
    system_metrics = get_system_metrics(UUID, SECRET)
  File "/opt/monitoring-agent.py", line 790, in get_system_metrics
    networking = _get_networking_stats()
  File "/opt/monitoring-agent.py", line 616, in _get_networking_stats
    input_accept_packets += int(line.split(' ')[0])
```
Seems to be caused by an issue parsing the output of iptables with fail2ban installed.

Output of iptables -L -vxn
```
Chain INPUT (policy ACCEPT 40160126 packets, 6700360565 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
    8120   684826 f2b-apache-xmlrpc  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
    8120   684826 f2b-apache-wplogin  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
  232380 12830364 f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
    pkts      bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 19839195 packets, 1626340859 bytes)
    pkts      bytes target     prot opt in     out     source               destination         

Chain blocked (0 references)
    pkts      bytes target     prot opt in     out     source               destination         

Chain f2b-apache-wplogin (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
    8120   684826 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain f2b-apache-xmlrpc (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
    8120   684826 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain f2b-sshd (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
  232380 12830364 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

Output of a print statement at line 616 -> print line.split(' ')

```
['', '', '231030', '12757476', 'f2b-sshd', '', '', 'tcp', '', '--', '', '*', '', '', '', '', '', '*', '', '', '', '', '', '', '0.0.0.0/0', '', '', '', '', '', '', '', '', '', '', '', '0.0.0.0/0', '', '', '', '', '', '', '', '', '', '', '', 'multiport', 'dports', '22']
```
The first two elements of the array at blank so fails trying to parse the int here
```
input_accept_packets += int(line.split(' ')[0])
```

**Comment by jparicka** [comment]
Thank you - I'll look into that.

**Comment by jparicka** [comment]
I'm on it #704 ...

**Comment by jparicka** [comment]
Note to self: Perhaps it is a good idea to make the networking stats conditional (on both the view, the agent and the template)?
This way you'll also get closer to the OS X compatibility...

**Comment by jparicka** [comment]
fixed
